Add prettier plugin that formats JSDoc comments and format code.
melink14/rikaikun pull request #217
Opened 2020-08-16 04:38 UTC by melink14

Update eslint config to prefer `@returns` over `@return` to match formatter.
This required mirroring some unrelated `valid-jsdoc` config due to configs not being merged.

2020-08-19 10:21 UTC, Stephie requested changes

2020-08-19 10:21 UTC, Stephie commented on extension/background.js
> +   * Set kanjiInfo option values Check each key in case there are new types of info
The line break disappeared!

2020-08-19 10:21 UTC, Stephie commented on extension/background.js
> +    /** Case 'nextDict': console.log('nextDict'); rcxMain.nextDict(); break; */
Is there a way to preserve the formatting of commented-out code?

2020-08-29 04:48 UTC, melink14 reviewed
Fixed.

> *[Reviewable](https://reviewable.io/reviews/melink14/rikaikun/217#-:-MFsXafR-QOf7BwgcQRb:bt2vr1b)* status: 0 of 8 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-08-30 06:43 UTC, Stephie approved these changes
> Reviewed 8 of 13 files at r2.
> *[Reviewable](https://reviewable.io/reviews/melink14/rikaikun/217)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-08-31 12:46 UTC, merged