refactor(promises): Add promise linting and fix current errors
melink14/rikaikun pull request #496
Opened 2021-05-22 05:48 UTC by melink14

- Add recommended lint warnings to config
- Prefer await over promise.then

2021-05-22 10:11 UTC, Stephie requested changes

2021-05-22 10:11 UTC, Stephie commented on extension/data.ts
> +        chrome.extension.getURL('data/' + 'names.dat')
`'data/names.dat'` (here and elsewhere)

2021-05-22 10:11 UTC, Stephie commented on extension/data.ts
> +    const loadDeinflectionData = this.loadDeinflectionData();
Inline these in `Promises.all()`

2021-05-22 10:18 UTC, Stephie approved these changes

2021-05-22 10:42 UTC, melink14 commented on extension/data.ts
> +    const loadDeinflectionData = this.loadDeinflectionData();
Done!

2021-05-22 10:43 UTC, melink14 commented on extension/data.ts
> +        chrome.extension.getURL('data/' + 'names.dat')
done!

2021-05-24 08:32 UTC, Stephie reviewed
So clean! 🤩

2021-05-24 08:32 UTC, Stephie commented on extension/data.ts
> +    // the name dictionaries into their proper place.
The code might be self-explanatory enough.

2021-05-28 12:13 UTC, merged

2021-05-31 12:00 UTC, melink14 commented
:tada: This PR is included in version 1.2.2 :tada:

The release is available on:
- [Chrome Web Store](https://chrome.google.com/webstore/detail/jipdnfibhldikgcjhfnomkfpcebammhp)
- [GitHub release](https://github.com/melink14/rikaikun/releases/tag/v1.2.2)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: